" Source custom mappings and plugins from ~/.vim
runtime maps.vim
runtime plugins.vim

syntax on                     " syntax highlighting

filetype plugin indent on     " filetype detection

set hidden                    " open new buffers without saving the current one
set noerrorbells              " silence error bells
set expandtab                 " tabs are spaces
set tabstop=2 softtabstop=2   " two space indent
set shiftwidth=2              " two space shift
set ignorecase                " ignore case by default...
set smartcase                 " ...but respect case once you use uppercase letters
set history=3000              " save command history
set encoding=utf8             " support unicode
set colorcolumn=0             " don't highlight columns
set noshowmode                " hide mode (airline shows it already)
set synmaxcol=0               " don't limit syntax highlighting
set mouse=a                   " allow the mouse
set autoread                  " Autoread when file is changed from outside of vim
set foldmethod=marker         " Default foldmethod

" See both current line number and relative numbers above/below
set number
set relativenumber

" Better defaults for splits
set splitbelow
set splitright

" Undo to you heart's content
set undolevels=1000
set undofile
set undodir=~/.vim/undodir

" You don't need swap files or backups if you have an undodir and Git
set noswapfile
set nobackup
set nowritebackup

" Wildmenu settings; see also plugin/wildignore.vim
set wildmenu                " Use wildmenu
set wildmode=list:longest   " Tab press completes and lists
silent! set wildignorecase  " Case insensitive, if supported

" Highlight searches; clear on reload
set hlsearch
set incsearch
if 1
  nohlsearch
endif

" Don't show startup splash screen
set shortmess+=I
" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

" Give more space for displaying messages
set cmdheight=2

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=50

highlight clear SignColumn

"" Colors

"" local version for testing (located in ~/.vim/colors)
" colorscheme fluidlan-vim
"" version from the plugin hosted on Github
colorscheme fluidlan

set termguicolors
hi Normal     ctermbg=NONE guibg=NONE
hi LineNr     ctermbg=NONE guibg=NONE
hi SignColumn ctermbg=NONE guibg=NONE
