syntax on

filetype plugin indent on

" Source custom mappings and plugins from ~/.vim
runtime maps.vim
runtime plugins.vim

set hidden
set noerrorbells
set tabstop=2 softtabstop=2
set shiftwidth=2
set expandtab
set ignorecase
set smartcase
set noswapfile
set encoding=utf8
set synmaxcol=120
set number
set relativenumber
set nobackup
set nowritebackup
set undodir=~/.vim/undodir
set history=3000
set undolevels=1000
set splitbelow
set splitright
set undofile
set incsearch
set colorcolumn=0
set noshowmode
set synmaxcol=0
set diffopt+=vertical
set mouse=a

" Wildmenu settings; see also plugin/wildignore.vim
set wildmenu                " Use wildmenu
set wildmode=list:longest   " Tab press completes and lists
silent! set wildignorecase  " Case insensitive, if supported

" Highlight completed searches; clear on reload
set hlsearch
if 1
  nohlsearch
endif

" Don't show startup splash screen
set shortmess+=I
" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

" Give more space for displaying messages
set cmdheight=2

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=50

highlight clear SignColumn

"" File tree (netrw)
let g:netrw_browse_split=4
let g:netrw_banner = 0
let g:netrw_winsize = 25
let g:netrw_liststyle = 3
let g:netrw_list_hide=netrw_gitignore#Hide()
" Hide hidden files
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'


"" Colors

"" local version for testing (located in ~/.vim/colors)
" colorscheme fluidlan-vim
"" version from the plugin hosted on Github
colorscheme fluidlan

set termguicolors
hi Normal     ctermbg=NONE guibg=NONE
hi LineNr     ctermbg=NONE guibg=NONE
hi SignColumn ctermbg=NONE guibg=NONE

