#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# Shared login tasks (atuin, Hyprland auto-start, etc.)
[ -f ~/.shell/login ] && . ~/.shell/login

command -v atuin &>/dev/null && eval "$(atuin init bash)"
