#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap 'rm -f "$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$$.tags" --exclude=node_modules --exclude=.firebase --exclude=__sapper__ --exclude=.vscode
mv "$$.tags" "tags"
